# Generated by Django 4.1.2 on 2022-10-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_date_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_delivery',
        ),
    ]
