# Generated by Django 4.1.2 on 2022-10-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cash',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cash',
            name='quantity',
        ),
    ]
