# Generated by Django 4.1.2 on 2022-10-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_customer_password_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
