# Generated by Django 4.1.2 on 2022-10-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_price_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='TotalPrice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
